[package]
name = "all_things_test"
version = "0.1.0"
edition = "2018"

[dependencies]
hyper = { version = "0.14.15", features = ["full"] }
tokio = { version = "1.15.0", features = ["full"] }
regex = "1.5.4"
mysql = "*"
